version: '3.7'

services:
    db:
      container_name: wordpress_db
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      env_file: ./code/db/.env
      # volumes:
      #   - db_data:/var/lib/mysql
      #   - ./code/db/backup-file.sql:/docker-entrypoint-initdb.d/backup-file.sql
      ports:
        - "3306"

    web:
      container_name: wordpress_web
      build:
        context: .
        dockerfile: web.dockerfile
      volumes:
        - ./code/web:/var/www/html
      ports:
        - "9000"
      depends_on:
        - db

    nginx:
      container_name: wordpress_nginx
      build:
        context: .
        dockerfile: nginx.dockerfile
      volumes:
        - ./code/web:/var/www/html
        - ./code/nginx/conf.d:/etc/nginx/conf.d
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - web
          # volumes:
          #   db_data:
